"""The claims this repository makes about itself (design document section 112).

Every number in these documents that went stale did so because somebody typed
it: README said a 165-page manual when it was 173, and the manual said 1,560
tests when there were more than 1,600. Neither was untrue when it was written,
and nothing in the suite noticed.

So the counted claims are measured and written between markers, the conformance
matrix is data rather than prose, and these tests fail when either drifts.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
TOOL = ROOT / "tools" / "conformance.py"

sys.path.insert(0, str(ROOT / "tools"))


@pytest.fixture(scope="module")
def matrix():
    import conformance

    return conformance.load_matrix()


class TestTheMatrixCoversTheDocument:
    def test_every_section_appears_exactly_once(self, matrix) -> None:
        """The check that makes the matrix worth reading."""
        import conformance

        titles = conformance.section_titles()
        listed = [row["section"] for row in matrix]
        assert sorted(listed) == sorted(titles)
        assert len(listed) == len(set(listed))

    def test_the_titles_come_from_the_document(self, matrix) -> None:
        """So a renamed section cannot leave a stale row behind."""
        import conformance

        titles = conformance.section_titles()
        for row in matrix:
            assert row["title"] == titles[row["section"]]

    def test_every_state_is_one_of_the_four(self, matrix) -> None:
        import conformance

        for row in matrix:
            assert row["state"] in conformance.STATES

    def test_anything_less_than_built_explains_itself(self, matrix) -> None:
        """A bare "partial" is a claim with no content."""
        for row in matrix:
            if row["state"] != "implemented":
                assert row.get("note"), f"section {row['section']} is {row['state']} with no note"

    def test_every_refusal_has_a_reason(self, matrix) -> None:
        """Refusing something the design asks for is a position, not a shrug."""
        for row in matrix:
            for refusal in row.get("refuses") or []:
                assert refusal.get("item")
                assert len(refusal.get("why", "")) > 80, f"§{row['section']}: thin reasoning"

    def test_the_known_refusals_are_recorded(self, matrix) -> None:
        """The four decisions taken against the document, by section."""
        refused = {
            row["section"]: [item["item"] for item in row.get("refuses") or []]
            for row in matrix
            if row.get("refuses")
        }
        assert "script" in refused[8][0]
        assert "embedding" in refused[59][0]
        assert "semantic" in refused[67][0]
        assert "GPU" in refused[69][0]


class TestTheRenderedMatrixIsCurrent:
    def test_it_matches_the_data(self) -> None:
        """`--check` is what CI runs; this is the same question, locally."""
        result = subprocess.run(
            [sys.executable, str(TOOL), "--check"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            timeout=600,
        )
        assert result.returncode == 0, result.stdout + result.stderr

    def test_the_rendered_file_says_it_is_generated(self) -> None:
        text = (ROOT / "docs" / "CONFORMANCE.md").read_text(encoding="utf-8")
        assert "Do not edit this file" in text


class TestCountedClaims:
    def test_the_readme_page_count_matches_the_manual(self) -> None:
        pypdf = pytest.importorskip("pypdf")
        manual = ROOT / "docs" / "Cacophony-Manual.pdf"
        if not manual.is_file():
            pytest.skip("no built manual")

        pages = len(pypdf.PdfReader(str(manual)).pages)
        readme = (ROOT / "README.md").read_text(encoding="utf-8")
        claimed = re.search(r"<!-- claim:pages -->([\d,]+)<!-- /claim -->", readme)
        assert claimed, "README no longer marks its page count"
        assert int(claimed.group(1).replace(",", "")) == pages

    def test_the_manuals_test_count_is_marked(self) -> None:
        """Marked rather than correct: the count changes with this very file."""
        source = (ROOT / "docs" / "manual" / "src" / "12-operating.html").read_text(
            encoding="utf-8"
        )
        assert re.search(r"<!-- claim:tests -->[\d,]+<!-- /claim -->", source)


class TestTheEstimateNamesTheUnitsTheDesignAsks:
    """Section 69 lists four units. Three are estimated; one is refused.

    LLM tokens, output storage and memory are produced. GPU generation time is
    not, and the refusal is recorded in the conformance matrix rather than
    answered with a number nobody could stand behind: it depends on how long a
    step takes on the provider's hardware, and no adapter reports that.
    """

    SCHEMA = {
        "ticket": {
            "count": 1_000,
            "fields": {
                "id": {"type": "integer", "generator": "sequence"},
                "summary": {
                    "type": "text",
                    "semantic": "a one-line summary",
                    "generator": "llm",
                    "on_unavailable": "placeholder",
                    "constraints": {"max_length": 400},
                },
            },
        }
    }

    def _estimate(self, schema=None):
        from helpers import compile_from

        compiled = compile_from(schema or self.SCHEMA)
        assert compiled.plan is not None
        return compiled.plan.estimate

    def test_tokens_come_from_the_declared_length(self) -> None:
        """400 characters is about a hundred tokens, a thousand times over."""
        estimate = self._estimate()
        assert estimate.llm_calls == 1_000
        assert estimate.llm_tokens == pytest.approx(100_000, rel=0.01)

    def test_an_explicit_max_tokens_wins(self) -> None:
        import copy

        schema = copy.deepcopy(self.SCHEMA)
        schema["ticket"]["fields"]["summary"]["max_tokens"] = 32
        assert self._estimate(schema).llm_tokens == 32_000

    def test_a_field_with_no_model_needs_no_tokens(self) -> None:
        schema = {
            "e": {"count": 500, "fields": {"n": {"type": "integer", "generator": "sequence"}}}
        }
        assert self._estimate(schema).llm_tokens == 0

    def test_memory_does_not_grow_with_the_dataset(self) -> None:
        """Section 31's claim, stated as an estimate rather than a hope."""
        import copy

        small = self._estimate()
        larger = copy.deepcopy(self.SCHEMA)
        larger["ticket"]["count"] = 10_000_000
        assert self._estimate(larger).peak_memory_bytes == small.peak_memory_bytes
        assert self._estimate(larger).estimated_bytes > small.estimated_bytes

    def test_the_plan_prints_both(self) -> None:
        from typer.testing import CliRunner

        from cacophony.cli.main import app

        result = CliRunner().invoke(app, ["plan", str(ROOT / "templates" / "helpdesk.yaml")])
        assert result.exit_code == 0, result.stdout
        assert "tokens" in result.stdout
        assert "memory" in result.stdout
